# Conway's Steinway Configuration File
# This file demonstrates all available configuration options

# Board initialization type: "Random", "Static", or "FurElise"
board_type = "Random"

# Enable or disable audio output
audio_enabled = true

# Generation limit: use "Limited" with a number or "Unlimited"  
# Default: Unlimited (except FurElise ALWAYS uses 80 for full song, ignoring this setting)
# Examples:
# generations = { Limited = 50 }      # Run for 50 generations
# generations = "Unlimited"           # Run indefinitely (default)

generations = "Unlimited"

# Delay between steps in milliseconds (ignored if tempo_bpm is set)
step_delay_ms = 200

# Musical tempo in beats per minute (optional, overrides step_delay_ms)
# Examples:
# tempo_bpm = 120.0    # Moderate tempo  
# tempo_bpm = 126.0    # Für Elise tempo (set automatically)
# Leave commented to use step_delay_ms instead
# tempo_bpm = 120.0