[package]
name = "audio"
version = "0.1.0"
edition = "2021"
description = "Audio module for Conway's Steinway"

[dependencies]
rodio = "0.17"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
