[global]
# Enable PEP 582 support
pep582 = true

[python]
# Specify Python version requirements
requires = ">=3.13"

[install]
# PDM installation settings
cache = true
parallel = true

[venv]
# Virtual environment settings (fallback if PEP 582 not available)
location = "../.venv"