[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "conways-steinway"
version = "0.1.0"
description = "Conway's Steinway Python Implementation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.5.0",
]

[tool.pdm]
version = {source = "file", path = "__init__.py"}

# PDM global configuration
[tool.pdm.python]
requires = ">=3.13"

[tool.pdm.venv]
location = "../.venv"

[tool.pdm.install]
cache = true
parallel = true

# Enable PEP 582 support
[tool.pdm.options]
pep582 = true

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
]

[tool.pdm.scripts]
start = "python main.py"
test = "pytest"
update-pip = "python -m pip install --upgrade pip"



# Future enhancements (commented out for now)
# data-analysis = [
#    "numpy>=1.25.0", 
#    "matplotlib>=3.7.0",
# ]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.pdm.resolution]
allow-prereleases = false
respect-source-order = true

