---
name: Claude Code Integration

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude:
    # Skip running the action on the claude-code-action repository itself
    if: github.repository != 'anthropics/claude-code-action'
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

  notify_pr_closed:
    if: >-
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          direct_prompt: |
            PR #${{ github.event.pull_request.number }}
            "${{ github.event.pull_request.title }}"
            has been merged.

            Branch: ${{ github.event.pull_request.head.ref }}
            Merged by: ${{ github.event.pull_request.merged_by.login }}

            Changes will be available in the next release.
